fsb_streetmarket_api_furnitures_list:
    pattern:  /.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:list"
        _format: json
    requirements:
        _method: get
        _format: json

fsb_streetmarket_api_furniture_create:
    pattern:  /create.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:create"
        _format: json
    requirements:
        _method: post
        _format: json

fsb_streetmarket_api_furniture_get:
    pattern:  /{id}.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:detail"
        _format: json
    requirements:
        _method: get
        _format: json
        id: \d+

fsb_streetmarket_api_furniture_update:
    pattern:  /{id}/update.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:update"
        _format: json
    requirements:
        _method: put
        _format: json
        id: \d+

fsb_streetmarket_api_furniture_upload:
    pattern:  /{id}/upload.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:upload"
        _format: json
    requirements:
        _method: put
        _format: json
        id: \d+

fsb_streetmarket_api_furniture_delete:
    pattern:  /{id}/delete.{_format}
    defaults:
        _controller: "FsbStreetMarketApiBundle:V1/Resources/Furniture:delete"
        _format: json
    requirements:
        _method: delete
        _format: json
        id: \d+
