<?php

namespace Fsb\StreetMarket\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurnitureRepository extends EntityRepository
{
    public function findAll()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('f')
            ->from('FsbStreetMarketCoreBundle:Furniture', 'f')
            ->where($qb->expr()->isNotNull('f.removedAt'))
        ;

        return $qb->getQuery()->getResult();
    }

    public function findAllActive()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('f')
            ->from('FsbStreetMarketCoreBundle:Furniture', 'f')
            ->where($qb->expr()->isNotNull('f.removedAt'))
            ->andWhere($qb->expr()->eq('f.isHidden', ':isHidden'))
            ->setParameter('isHidden', false)
        ;

        return $qb->getQuery()->getResult();
    }

    public function findAllLatestActive($limit = null)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('f')
            ->from('FsbStreetMarketCoreBundle:Furniture', 'f')
            ->where($qb->expr()->isNotNull('f.removedAt'))
            ->andWhere($qb->expr()->eq('f.isHidden', ':isHidden'))
            ->setParameter('isHidden', false)
            ->orderBy('f.tookAt', 'DESC')
        ;

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }
}
